dist: trusty
language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10

install:
  - cd $TRAVIS_BUILD_DIR/jaxrs-api
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd $TRAVIS_BUILD_DIR/examples
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd $TRAVIS_BUILD_DIR/jaxrs-spec
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - cd $TRAVIS_BUILD_DIR/jaxrs-api
  - mvn test -B
  - cd $TRAVIS_BUILD_DIR/examples
  - mvn test -B
  - cd $TRAVIS_BUILD_DIR/jaxrs-spec
  - mvn test -B
